on: pull_request

jobs:
  dispatch-private:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger private repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            https://api.github.com/repos/outrunmr/private-eepo/dispatches \
            -d '{"event_type":"run-from-public","client_payload":{"pr_number":${{ github.event.number }}}}'
